### ISSUE TITLE
update the plugin store's version to compatible 231.* IDE

### ISSUE THREAD

**Issue by xiaoxiaowesley** [google/intellij-gn-plugin#25]
I see that you have updated the modification to be compatible with [version Add 231.* IDE](https://github.com/google/intellij-gn-plugin/commit/89e08f8cb53667279f69b2e1589e6df2f1b7528a)
. Could you update the JetBrains marketplace?

**Comment by bc-lee** [comment]
The latest version [0.1.3-13-g89e08f8](https://plugins.jetbrains.com/plugin/14705-gn/versions/stable/313381) is compatible with 231.* IDEs.
Due to my mistake, the Changelog will say that only up to 223.* are compatible.
